const mongoose = require("mongoose");

const reportSchema = new mongoose.Schema(
  {
    department: {
      type: String,
      required: true,
    },
    entryDate:{
        type:Date,
        required:true
    },
    inputs: {
      b3: { type: Number, default: 0 },
      c4: { type: Number, default: 0 },
      d4: { type: Number, default: 0 },
      e4: { type: Number, default: 0 },
      f4: { type: Number, default: 0 },
      g4: { type: Number, default: 0 },
      h4: { type: Number, default: 0 },
      c5: { type: Number, default: 0 },
      d5: { type: Number, default: 0 },
      e5: { type: Number, default: 0 },
      f5: { type: Number, default: 0 },
      g5: { type: Number, default: 0 },
      h5: { type: Number, default: 0 },
      h6: { type: Number, default: 0 },
      b11: { type: Number, default: 0 },
      b12: { type: Number, default: 0 },
      b13: { type: Number, default: 0 },
      b14: { type: Number, default: 0 },
      b15: { type: Number, default: 0 },
      b16: { type: Number, default: 0 },
      b18: { type: Number, default: 0 },
      b17: { type: Number, default: 0 },
      b19: { type: Number, default: 0 },
      b20: { type: Number, default: 0 },
      b21: { type: Number, default: 0 },
      b22: { type: Number, default: 0 },
      b23: { type: Number, default: 0 },
      b24: { type: Number, default: 0 },
      b25: { type: Number, default: 0 },
      b26: { type: Number, default: 0 },
      b27: { type: Number, default: 0 },
      b28: { type: Number, default: 0 },
      b29: { type: Number, default: 0 },
      b30: { type: Number, default: 0 },
      b31: { type: Number, default: 0 },
      b32: { type: Number, default: 0 },
      b33: { type: Number, default: 0 },
      b34: { type: Number, default: 0 },
      b35: { type: Number, default: 0 },
      b36: { type: Number, default: 0 },
      b37: { type: Number, default: 0 },
      b38: { type: Number, default: 0 },
      b39: { type: Number, default: 0 },
      b40: { type: Number, default: 0 },
      b41: { type: Number, default: 0 },
      b42: { type: Number, default: 0 },
      b43: { type: Number, default: 0 },
      c8: { type: Number, default: 0 },
      d8: { type: Number, default: 0 },
      e8: { type: Number, default: 0 },
      f8: { type: Number, default: 0 },
      f12: { type: Number, default: 0 },
      g12: { type: Number, default: 0 },
      h12: { type: Number, default: 0 },
      f13: { type: Number, default: 0 },
      g13: { type: Number, default: 0 },
      h13: { type: Number, default: 0 },
      f14: { type: Number, default: 0 },
      g14: { type: Number, default: 0 },
      h14: { type: Number, default: 0 },
    },
    reports: {
      b4result: { type: Number, default: 0 },
      b5result: { type: Number, default: 0 },
      b6result: { type: Number, default: 0 },
      c6result: { type: Number, default: 0 },
      d6result: { type: Number, default: 0 },
      e6result: { type: Number, default: 0 },
      f6result: { type: Number, default: 0 },
      g6result: { type: Number, default: 0 },
      h6result: { type: Number, default: 0 },
      stockrecord: { type: Number, default: 0 },
      perdip: { type: Number, default: 0 },
      variance: { type: Number, default: 0 },
      perVar: { type: Number, default: 0 },
      avgmonth: { type: Number, default: 0 },
      avgdiff: { type: Number, default: 0 },
      ftera: { type: Number, default: 0 },
      gtera: { type: Number, default: 0 },
      htera: { type: Number, default: 0 },
      feighteen: { type: Number, default: 0 },
      geighteen: { type: Number, default: 0 },
      heighteen: { type: Number, default: 0 },
      heighteen: { type: Number, default: 0 },
      cashsales: { type: Number, default: 0 },
    },
  },
  { timestamps: true }
);

const ReportFile = mongoose.model("ReportFile", reportSchema);

module.exports = ReportFile;
