const mongoose = require("mongoose");

const InflowOutFlowSchema = new mongoose.Schema(
  { User:{type:String, required:true },
   Department:{type:String, required:true },
   Profit:{type:Number, required:true },
   Loss:{type:Number, required:true },
    Inflow: { type: Number, },
    Outflow: { type: Number, },
    NetFlow: { type: Number, },
    inputs: {
      c46: { type: Number, default: 0 },
      c47: { type: Number, default: 0 },
      c48: { type: Number, default: 0 },
      c49: { type: Number, default: 0 },
      c50: { type: Number, default: 0 },
      c51: { type: Number, default: 0 },
      c52: { type: Number, default: 0 },
      c53: { type: Number, default: 0 },
      c54: { type: Number, default: 0 },
      c55: { type: Number, default: 0 },
      c56: { type: Number, default: 0 },
      c57: { type: Number, default: 0 },
      c58: { type: Number, default: 0 },
      c59: { type: Number, default: 0 },
      e46: { type: Number, default: 0 },
      e47: { type: Number, default: 0 },
      e48: { type: Number, default: 0 },
      e49: { type: Number, default: 0 },
      e50: { type: Number, default: 0 },
      e51: { type: Number, default: 0 },
      e52: { type: Number, default: 0 },
      e53: { type: Number, default: 0 },
      e54: { type: Number, default: 0 },
      e55: { type: Number, default: 0 },
      e56: { type: Number, default: 0 },
      e57: { type: Number, default: 0 },
      e58: { type: Number, default: 0 },
      e59: { type: Number, default: 0 },
      f46: { type: String, default: "" }, // Text fields initialized as empty strings
      g46: { type: String, default: "" },
      f47: { type: String, default: "" },
      g47: { type: String, default: "" },
      f48: { type: String, default: "" },
      g48: { type: String, default: "" },
      f49: { type: String, default: "" },
      g49: { type: String, default: "" },
      f50: { type: String, default: "" },
      g50: { type: String, default: "" },
      f51: { type: String, default: "" },
      g51: { type: String, default: "" },
      f52: { type: String, default: "" },
      g52: { type: String, default: "" },
      f53: { type: String, default: "" },
      g53: { type: String, default: "" },
      f54: { type: String, default: "" },
      g54: { type: String, default: "" },
      f55: { type: String, default: "" },
      g55: { type: String, default: "" },
      f56: { type: String, default: "" },
      g56: { type: String, default: "" },
      f57: { type: String, default: "" },
      g57: { type: String, default: "" },
      b58: { type: String, default: "" },
      f58: { type: String, default: "" },
      g58: { type: String, default: "" },
      b59: { type: String, default: "" },
      f59: { type: String, default: "" },
      g59: { type: String, default: "" },
      date1: { type: Date, default: "" },
    },
  },
  { timestamps: true }
);


const InOutFlow= mongoose.model("InFlow_OutFlow", InflowOutFlowSchema);
module.exports = InOutFlow;;