const mongoose = require('mongoose');


const sbi01Report = new mongoose.Schema({
    username: { type: String, required: true },
    Department:{ type: String, required: true},
    Balance_Evening:{ type: Number, default: 0},
    Total_Fund_Stock: { type: Number, default: 0},
    Working_Cappital:{ type: Number, default: 0},
    inputs:{
        c6: { type: Number, default: 0 },
        c7: { type: Number, default: 0 },
        c8: { type: Number, default: 0 },
        c9: { type: Number, default: 0 },
        c9: { type: Number, default: 0 },
        c10: { type: Number, default: 0 },
        c11: { type: Number, default: 0 },
        c12: { type: Number, default: 0 },
        c13: { type: Number, default: 0 },
        c14: { type: Number, default: 0 },
        c15: { type: Number, default: 0 },
        c16: { type: Number, default: 0 },
        c17: { type: Number, default: 0 },
        c18: { type: Number, default: 0 },
        c19: { type: Number, default: 0 },
        c20: { type: Number, default: 0 },
        c21: { type: Number, default: 0 },
        c22: { type: Number, default: 0 },
        c23: { type: Number, default: 0 },
        c24: { type: Number, default: 0 },
        c25: { type: Number, default: 0 },
        c26: { type: Number, default: 0 },
        c27: { type: Number, default: 0 },
        c28: { type: Number, default: 0 },
        c29: { type: Number, default: 0 },
        c30: { type: Number, default: 0 },
        c31: { type: Number, default: 0 },
        c32: { type: Number, default: 0 },
        c33: { type: Number, default: 0 },
        c34: { type: Number, default: 0 },
        c35: { type: Number, default: 0 },
        c36: { type: Number, default: 0 },
        c37: { type: Number, default: 0 },
        c38: { type: Number, default: 0 },
        c39: { type: Number, default: 0 },
        d6: { type: Number, default: 0 },
        d7: { type: Number, default: 0 },
        d8: { type: Number, default: 0 },
        d9: { type: Number, default: 0 },
        d10: { type: Number, default: 0 },
        d11: { type: Number, default: 0 },
        d12: { type: Number, default: 0 },
        d13: { type: Number, default: 0 },
        d14: { type: Number, default: 0 },
        d15: { type: Number, default: 0 },
        d16: { type: Number, default: 0 },
        d17: { type: Number, default: 0 },
        e6: { type: Number, default: 0 },
        e7: { type: Number, default: 0 },
        e8: { type: Number, default: 0 },
        e9: { type: Number, default: 0 },
        e10: { type: Number, default: 0 },
        e11: { type: Number, default: 0 },
        e12: { type: Number, default: 0 },
        e13: { type: Number, default: 0 },
        e14: { type: Number, default: 0 },
        e15: { type: Number, default: 0 },
        e16: { type: Number, default: 0 },
        e17: { type: Number, default: 0 },
        j10: { type: Number, default: 0 },
        j11: { type: Number, default: 0 },
        f6: { type: Number, default: 0 },
        f7: { type: Number, default: 0 },
        f8: { type: Number, default: 0 },
        f9: { type: Number, default: 0 },
        f10: { type: Number, default: 0 },
        f11: { type: Number, default: 0 },
        f12: { type: Number, default: 0 },
        f13: { type: Number, default: 0 },
        f14: { type: Number, default: 0 },
        f15: { type: Number, default: 0 },
        f16: { type: Number, default: 0 },
        f17: { type: Number, default: 0 },
        i6: { type: Number, default: 0 },
        i7: { type: Number, default: 0 },
        i8: { type: Number, default: 0 },
        i9: { type: Number, default: 0 },
        i10: { type: Number, default: 0 },
        i11: { type: Number, default: 0 },
        i12: { type: Number, default: 0 },
        i13: { type: Number, default: 0 },
        i14: { type: Number, default: 0 },
        i15: { type: Number, default: 0 },
        i16: { type: Number, default: 0 },
        i17: { type: Number, default: 0 },
        e24: { type: Number, default: 0 },
        e25: { type: Number, default: 0 },
        e26: { type: Number, default: 0 },
        e27: { type: Number, default: 0 },
        date1: { type: Date, default: 0 },
        date2: { type: Date, default: 0 },
        date3: { type: Date, default: 0 },
        date4: { type: Date, default: 0 },
        date5: { type: Date, default: 0 },
        date6: { type: Date, default: 0 },
        date7: { type: Date, default: 0 },
        date8: { type: Date, default: 0 },
        date9: { type: Date, default: 0 },
        j13: { type: Number, default: 0 },
        j14: { type: Number, default: 0 },
        a32: { type: Number, default: 0 },
        a33: { type: Number, default: 0 },
        d32: { type: Number, default: 0 },
        
    },
    CalculatedValue:{
        totalsum:{ type: Number, default: 0 },
        j6result:{ type: Number, default: 0 },
        j7result:{ type: Number, default: 0 },
        j8result:{ type: Number, default: 0 },
        j9result:{ type: Number, default: 0 },
        j12result:{ type: Number, default: 0 },
        e16result:{ type: Number, default: 0 },
        balenv:{ type: Number, default: 0 },
        c34result:{ type: Number, default: 0 },
        workingcap:{ type: Number, default: 0 },
        e39result:{ type: Number, default: 0 },
    },
    
},{ timestamps: true }

);

const SBI_02_Bank = mongoose.model('SBI 02 Bank', sbi01Report);
module.exports= SBI_02_Bank;